# Generated by Django 5.1.1 on 2024-11-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='unhealthy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_status', models.CharField(max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_monitoring.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1_response', models.BooleanField(default='N/A')),
                ('question_2_response', models.BooleanField(default='N/A')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_monitoring.session')),
            ],
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_engaged', models.IntegerField()),
                ('distance_while_active', models.IntegerField()),
                ('hand_position', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('compression', models.IntegerField()),
                ('recoil', models.IntegerField()),
                ('watched_animation', models.BooleanField()),
                ('sessions_played', models.IntegerField()),
                ('session_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='remote_monitoring.session')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=100)),
                ('secondary_email', models.EmailField(max_length=100)),
                ('optional1_email', models.EmailField(max_length=100)),
                ('optional2_email', models.EmailField(max_length=100)),
                ('optional3_email', models.EmailField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='remote_monitoring.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine'], name='remote_moni_machine_d43b86_idx'), models.Index(fields=['primary_email', 'secondary_email', 'optional1_email', 'optional2_email', 'optional3_email'], name='remote_moni_primary_b5dd62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['machine', 'session_status'], name='remote_moni_machine_603119_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['session'], name='remote_moni_session_b4b21a_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['question_1_response', 'question_2_response'], name='remote_moni_questio_529358_idx'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['session_status'], name='remote_moni_session_cc9903_idx'),
        ),
    ]
