# Generated by Django 5.1.1 on 2024-11-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='remote_moni_machine_603119_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='remote_moni_session_b4b21a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermetrics',
            name='remote_moni_session_cc9903_idx',
        ),
        migrations.RemoveField(
            model_name='session',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usermetrics',
            name='session_status',
        ),
        migrations.AddField(
            model_name='survey',
            name='usermetrics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='remote_monitoring.usermetrics'),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='remote_monitoring.machine'),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='session',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='remote_monitoring.session'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['usermetrics'], name='remote_moni_usermet_889a16_idx'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['session', 'machine'], name='remote_moni_session_49021c_idx'),
        ),
    ]
