# Generated by Django 5.1.1 on 2024-11-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_monitoring', '0003_alter_survey_question_1_response_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='usermetrics',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='remote_monitoring.survey'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['session', 'machine', 'survey'], name='remote_moni_session_b398c5_idx'),
        ),
    ]
