# Generated by Django 5.1.1 on 2024-11-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_monitoring', '0004_remove_survey_remote_moni_usermet_889a16_idx_and_more'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='usermetrics',
            name='machine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='remote_monitoring.machine'),
        ),
        migrations.AlterField(
            model_name='usermetrics',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='remote_monitoring.session'),
        ),
        migrations.AlterField(
            model_name='usermetrics',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='remote_monitoring.survey'),
        ),
    ]
